apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Y3+57Ej7KglixOOxO3ooOUizs+ShmAxQ/2RM+DmWvh1UNs2w,iv:AVnJS4qyLvHVeg9KZBfP7LEkLS/+sq8zi2B9KT2FpeM=,tag:CgCaiccUAh5GqLX2zZR9FQ==,type:str]
  MAIN_DOMAIN: ENC[AES256_GCM,data:Jw9ii3nq5kAe77Pa,iv:x1QD7Qk5VVL+6uLm2DA42cAMrrIBtTr2R7jG/e7utSo=,tag:MYf74cqWRgp8E69oJtvvVQ==,type:str]
  PRIVATE_DNS_PRIMARY: ENC[AES256_GCM,data:EsjiS7SkSmdwIzo=,iv:tBBB4iOIgX/9AQcKRmOjbKIWo6icm82+n4N74E5UMRE=,tag:A5pHiQmYQH2uSeNryJ1vOA==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:+Hz3gmXFN66s,iv:j1+H7Ovcfzb4qWHJbhUlQYWjbBFn4hi3zxkvE77I5Ds=,tag:aMBp7g4lKPJuRR73t+i/VA==,type:str]
sops:
  age:
    - recipient: age14c693pdqe6ucz358tteussmwt96fyqz2zs8d656td2av3y0s7ugqklja8z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveCt1a0R6M0dPVlZLZmhu
        aHNnQmd4SHlPT1RmTDl3anpIbEVHbjZDc1RFCkxxeW1henpjQS9yY2pLY0dEME12
        cTVjSTVpaEJmUEVTenlrZWI5MlFPZHcKLS0tIHZUM1lRUDdIUThiZ3prdmFtNDZ1
        RUZMY0R6RXViY1FYeUE0RnFkTit0ajgKshP4R2Qf3NVIxWzwOP8aEXdZSP8yOkkN
        3swDHrcyrfCWbEBUVoWE1VMqoldpQ//YmJD/KQ/UJ2pZoJJ0riRwWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-27T22:40:24Z"
  mac: ENC[AES256_GCM,data:9LzNAf4y1x4/9dAFjKlRN9ugOCbdmZuk1Ul5SkqgVkDU9woLgzyx9gCS4BmzwiVoUqTxc2E4ZVjv8FMSOZlLAlS2p+zQevEg7dd+B380CpIB4ZIe4o9+mpD5Sirla9XPr1QaJqHfbKkbW7DZYrO9jDsK7wzErahl+I433xK9Vn0=,iv:34KPOekx6vDic+SIEDalnj613hoMT7tbDUR4ojgi9Yw=,tag:ZmATsmAuHS0aN5uisOXkDA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
