apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Y3+57Ej7KglixOOxO3ooOUizs+ShmAxQ/2RM+DmWvh1UNs2w,iv:AVnJS4qyLvHVeg9KZBfP7LEkLS/+sq8zi2B9KT2FpeM=,tag:CgCaiccUAh5GqLX2zZR9FQ==,type:str]
  MAIN_DOMAIN: ENC[AES256_GCM,data:Jw9ii3nq5kAe77Pa,iv:x1QD7Qk5VVL+6uLm2DA42cAMrrIBtTr2R7jG/e7utSo=,tag:MYf74cqWRgp8E69oJtvvVQ==,type:str]
  PRIVATE_DNS_PRIMARY: ENC[AES256_GCM,data:qRjcrCAbG/671SUb,iv:ZNz+ScbhWLa5itoQk2CJCrhvC7rwQbE0OoqAqameccM=,tag:kO9h33xJAgS+8sy0WQ8ryg==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:+Hz3gmXFN66s,iv:j1+H7Ovcfzb4qWHJbhUlQYWjbBFn4hi3zxkvE77I5Ds=,tag:aMBp7g4lKPJuRR73t+i/VA==,type:str]
sops:
  age:
    - recipient: age14c693pdqe6ucz358tteussmwt96fyqz2zs8d656td2av3y0s7ugqklja8z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveCt1a0R6M0dPVlZLZmhu
        aHNnQmd4SHlPT1RmTDl3anpIbEVHbjZDc1RFCkxxeW1henpjQS9yY2pLY0dEME12
        cTVjSTVpaEJmUEVTenlrZWI5MlFPZHcKLS0tIHZUM1lRUDdIUThiZ3prdmFtNDZ1
        RUZMY0R6RXViY1FYeUE0RnFkTit0ajgKshP4R2Qf3NVIxWzwOP8aEXdZSP8yOkkN
        3swDHrcyrfCWbEBUVoWE1VMqoldpQ//YmJD/KQ/UJ2pZoJJ0riRwWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-28T20:42:12Z"
  mac: ENC[AES256_GCM,data:RRQ1+3twdvPa3kCzcPTmFQ+oa9BZ/GaRm7IZ2MrcoYcWwOzcmXJ7ZuHQ5jPeFBLjf+yoGR086u3lxw7lZu8d7SI/rpawG8s8s3TXQtWxqboB1T5QFnK0fJ5Ii0oKGvg+e3bi1g7bCHlBPeNpmPPfSVhpgYNIqL4e56vP9r0+P+0=,iv:QDSgYtM2L1NxZU9CF9BVyoTqGFgeyHOWJCGTr+un6Ak=,tag:iMn1Oy151pzsksjQ7qCTPw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
