[env]
KUBECONFIG = "{{config_root}}/kubernetes/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/talos/talosconfig"
# File paths
BOOTSTRAP_DIR = "{{config_root}}/bootstrap"
KUBERNETES_DIR = "{{config_root}}/kubernetes"
ROOT_DIR = "{{config_root}}"
SCRIPTS_DIR = "{{config_root}}/scripts"
TALOS_DIR = "{{config_root}}/talos"

_.python.venv = { path = "{{config_root}}/.venv", create = true }

[settings]
pipx_uvx = true

[tools]
"aqua:astral-sh/uv" = "0.9.4"
"pipx:flux-local" = "7.11.0"

"aqua:cilium/cilium-cli" = "0.18.8"
"aqua:cli/cli" = "2.82.1"
"aqua:cloudflare/cloudflared" = "2025.10.0"
"aqua:FiloSottile/age" = "1.2.1"
"aqua:fluxcd/flux2" = "2.7.2"
"aqua:getsops/sops" = "3.11.0"
"aqua:go-task/task" = "3.45.4"
"aqua:helm/helm" = "3.19.0"
"aqua:helmfile/helmfile" = "1.1.7"
"aqua:jqlang/jq" = "1.8.0"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:kubernetes/kubectl" = "1.33.1"
"aqua:mikefarah/yq" = "4.48.1"
"aqua:mitsuhiko/minijinja" = "2.12.0"
"aqua:siderolabs/talos" = "1.11.2"
"aqua:yannh/kubeconform" = "0.7.0"
