[env]
KUBECONFIG = "{{config_root}}/kubernetes/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/talos/talosconfig"
# File paths
BOOTSTRAP_DIR = "{{config_root}}/bootstrap"
KUBERNETES_DIR = "{{config_root}}/kubernetes"
ROOT_DIR = "{{config_root}}"
SCRIPTS_DIR = "{{config_root}}/scripts"
TALOS_DIR = "{{config_root}}/talos"

_.python.venv = { path = "{{config_root}}/.venv", create = true }

[settings]
pipx_uvx = true

[tools]
"aqua:astral-sh/uv" = "0.10.2"
"pipx:flux-local" = "8.1.0"

"aqua:cilium/cilium-cli" = "0.19.1"
"aqua:cli/cli" = "2.86.0"
"aqua:cloudflare/cloudflared" = "2026.2.0"
"aqua:FiloSottile/age" = "1.2.1"
"aqua:fluxcd/flux2" = "2.7.5"
"aqua:getsops/sops" = "3.11.0"
"aqua:go-task/task" = "3.48.0"
"aqua:helm/helm" = "4.1.1"
"aqua:helmfile/helmfile" = "1.2.3"
"aqua:jqlang/jq" = "1.8.0"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:kubernetes/kubectl" = "1.33.1"
"aqua:mikefarah/yq" = "4.52.2"
"aqua:mitsuhiko/minijinja" = "2.15.1"
"aqua:siderolabs/talos" = "1.12.4"
"aqua:yannh/kubeconform" = "0.7.0"
