---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
spec:
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt-production-shortlived
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always
  duration: 160h
  usages:
    - digital signature
  dnsNames:
    - ${SECRET_DOMAIN}
    - "*.${SECRET_DOMAIN}"
