---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  TIMEZONE: "America/Toronto"
  NGINX_INT_IPV4: 192.168.23.90
  NGINX_INT_IPV6: fdd5:aa8:9535:23::90
  GATEWAY_INT_IPV4: 192.168.23.80
  GATEWAY_INT_IPV6: fdd5:aa8:9535:23::80
  GATEWAY_EXT_IPV4: 192.168.23.81
  GATEWAY_EXT_IPV6: fdd5:aa8:9535:23::81
